### ISSUE TITLE
Dependency BusIO missing

### ISSUE THREAD

**Issue by kopp** [adafruit/Adafruit_LSM303DLH_Mag#2]
The dependency to Adafruits BusIO is missing in the description.

- Arduino board:  Uno (does not matter)

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.9 (does not matter)

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

1. Install this library (v1.1.0)
1. Install Adafruit Unified Sensor (v1.0.3)
1. Create a minimal example that just contains

```
#include <Adafruit_LSM303_Accel.h>
#include <Adafruit_Sensor.h>
#include <Wire.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

You will get a compilation error:

> fatal error: Adafruit_BusIO_Register.h: No such file or directory

- Proposed fix:

Add the library [BusIO](https://github.com/adafruit/Adafruit_BusIO) to the list of dependencies of this library.

**Comment by kopp** [comment]
oops, sorry.  This went into the wrong repo.  I actualy wanted to report it [here](https://github.com/adafruit/Adafruit_LSM303_Accel/issues/3).

**Comment by rspatton** [comment]
This actually applies to this repo as well. BusIO isn't specified as a dependency in the README.
