### ISSUE TITLE
Where do assign the calibration Min and Max value?

### ISSUE THREAD

**Issue by minhanh1234** [adafruit/Adafruit_LSM303DLH_Mag#4]
Good day,
After you run the calibration.ino, where do we adjust the adafruit_LSM303DLH_Mag?
I am not sure what I do with the Min and Max value after the calibration.

My LSM303 compass is not accurate.

Minh N

**Comment by ladyada** [comment]
this guide has info 
https://learn.adafruit.com/adafruit-sensorlab-magnetometer-calibration

**Comment by ajlapp** [comment]
Actually this doesn't have the info...this just informs us how to get the values.  I think the question is how we do we set the min and max values for the sensor?  I'm also struggling with this.  Thanks.
